### PR TITLE
Fix Win32 library install

### PR DESCRIPTION
**Pull request by ferdnyc**
I left out a path, so the Windows builds aren't installing their DLL. (The DLL on Windows is installed to the RUNTIME DESTINATION of the target, so we should specify that path too.) Also, the COMPONENT isn't necessary right now, only for EXPORT targets.

### CODE REVIEW

**Comment by ferdnyc** [comment]
@jonoomph If you could please merge this, _worst_ case it may have no effect at all, but I believe it will fix the Win32 daily builds issue reported at OpenShot/openshot-qt#2841

**Comment by jonoomph** [comment]
LGTM!

**Comment by ferdnyc** [comment]
@jonoomph The question is, did it fix the Windows daily builds?

...I suppose I should download one and check.

**Comment by ferdnyc** [comment]
Just ran through the full install process under Win32 WINE on Linux, and even launched OpenShot. Crashed in the hardware-decoding lookups when I tried to open Preferences, but it was never expected to be _functional_ and that's a _lot_ farther than I got when it was broken. (The installer wouldn't even launch, then.)

So, yeah... without actually testing on Windows, I'm gonna call OpenShot/openshot-qt#2841 fixed.

**Pull request merged**
