### PR TITLE
WIP: Upgrade to Juce 5.4.3

### PR DESCRIPTION
**Pull request by ferdnyc**
I'll just cut-and-paste from [my comment](https://github.com/OpenShot/libopenshot-audio/issues/33#issuecomment-478015134) on #33 :

Ohhh-kay. So, I now have "juce5" branches in both of my library forks ([ferdnyc/libopenshot-audio](https://github.com/ferdnyc/libopenshot-audio) and [ferdnyc/libopenshot](https://github.com/ferdnyc/libopenshot-audio)) which I have used to successfully build, package, and install working libraries based on Juce 5.4.3, running on Linux. And, yes, libopenshot-audio now builds under GCC 9 on Fedora 30 as well (but more on that in a second)...

Along the way, I made some pretty major changes to the build environment. The core of those changes were necessitated by the new Juce code structure. (I genuinely believe the new Juce setup is superior, which is why I consider it worth adjusting our build process _to_, rather than trying to swim against the tide in order to preserve legacy cruft.) 

However, along the way I took the opportunity to "spruce up" other aspects of the build in areas where it was lacking. (Like the lack of library path discovery for `libasound` and `libfreetype` in libopenshot-audio, or the convoluted header file structure it outputs, which then became convoluted `#include` structure in `libopenshot`.) The reason I qualified my initial statement with "on Linux" is because, in some instances where my changes necessitate the addition of new packages or libraries to the build configs, I made those additions on the only platform I have access to (Linux), knowing full well that the Windows and Mac builds will break until they've been adjusted as well. 

Which is to say, I explicitly **don't believe** that libopenshot-audio can be compiled under Windows or MacOS using the code on my `juce5` branch. (My changes to libopenshot would be cross-platform, so it should be fine once libopenshot-audio can be built.) The changes required should be _fairly_ minor, but changes will be required. (It should also be fairly simple to selectively undo some of the decisions I made for Linux, as a way of fixing the build on other platforms without having to change their builds. If that approach was preferred.)

Anyway, here's the orbital-satellite view of what I changed in those branches...

#### `libopenshot-audio`
* Generated `JuceLibraryCode` from the Juce 5.4.3 sources, using GPLv3'd Projucer.
    * Unnecessary modules are no longer included, streamlining the source tree.
    * Explicitly set `JUCE_USE_CURL` to 0 in the project settings, as Linux default is 1.
    * Set `JUCE_INCLUDE_ZLIB_CODE` to 0, to use the system zlib instead. 
    This is one of the items that will require Windows and MacOS build changes to compile successfuly on those platforms. However, in addition to being more compliant with the packaging standards for Linux distros, I believe the bundled zlib code may have been the cause of those Windows crashes we were seeing. (Or I could be wrong, and unbundling it from libopenshot-audio could make that situation even worse.) Regardless, every platform has a native zlib shared library trivially accessible, to link in with libopenshot-audio.
* Removed `using namespace std;` from `include/Version.h`, taking to heart OpenShot/libopenshot#204
* Updated the `CMakeLists.txt` build config for the Juce files, so that:
    * The Linux build tree now uses standard CMake `find_package()` modules to detect the configuration for additional dependencies:
        * Freetype (previously hardcoded paths)
        * ALSA (previously no detection, "asound" was  just listed as a library to link in, and assumed to be present)
        * ZLIB (previously not a dependency as it was bundled)
    * Source-file detection for the Juce tree now uses the set of `include_<module>.cpp` files at the root of the `JuceLibraryCode` tree, instead of descending into the `modules/` tree. Juce 5.4.3 is organized in such a way that recursing into `modules/` is no longer supported or necessary.
    * `JuceLibraryCode/modules/` is added to `INCLUDE_DIRECTORIES` when building the source tree. This is necessitated by the use of `#include <juce_$modulename/header.h>` style includes in the `JuceLibraryCode/include_juce_$modulename.cpp` files, rather than the relative-path-based `#include`s used within the `modules/` tree.

        The new code structure requires include paths to be properly set up when building the library itself, just like when building code written against the library, which improves the odds everything will be configured the same way.
    * In concert with the previous change, the Juce header files are now _installed_ at the root of the target include dir. In other words...
        * **Old path:** `/usr/include/libopenshot-audio/JuceLibraryCode/modules/juce_core/juce_core.h`
          **New path:** `/usr/include/libopenshot-audio/juce_core/juce_core.h`
        * **Old path:** `/usr/include/libopenshot-audio/JuceLibraryCode/JuceHeader.h`
          **New path:** `/usr/include/libopenshot-audio/JuceHeader.h`

        This required `#include` changes to a few header files in libopenshot (more on that later), but makes for a much cleaner installation that only requires a single `-I/usr/include/libopenshot-audio` include path to correctly pick up all of the headers.
    * Juce's `AppConfig.h` is also now installed in the `libopenshot-audio` include dir, as it's required when using the Juce headers.

    * Included the `isfinite()` fix (cleaner version) from #19, which is still necessary when building the ruby bindings for libopenshot.

Marking this "WIP" because it still requires (hopefully pretty minor) changes to the Windows and MacOS build configs in `CMakeLists.txt`, or builds will fail on those platforms. I don't have the resources to make or test those changes, so it's not "WIP" in the sense of expecting any more commits from me. I've taken it as far as I can.

Fixes: #33
Fixes: OpenShot/libopenshot#42

### CODE REVIEW

**Comment by ferdnyc** [comment]
> I've taken it as far as I can.

OK, not quite. Let me see what I can do about enabling `C++11` support, to make Travis happy. (Fedora has that on by default, so it didn't come up locally.)

**Comment by jonoomph** [comment]
@ferdnyc this is terrific! Thanks so much for taking on this effort, I really appreciate the help with this one! A few thoughts off the top of my head:

1. We don't currently use AudioProcesssors, but I am about to start implementing some JUCE audio effects, which I believe will require this module (I could be wrong)
2. Build environment changes for Windows and Mac should be simple to overcome, and I'll take on that challenge.
3. In order to see our breakages on Windows and Mac, I would like to move your 2 juce5 branches into the /OpenShot/ repos... so our build servers will attempt to use them. I can push them (but just FYI this will happen in the next couple hours). I believe you should still have commit access to them in the OpenShot repo as well... so feel free to continue to merge changes into them.

Hopefully enabling AudioProcessors doesn't throw a wrench into this plan. =)

**Comment by jonoomph** [comment]
Merged into https://github.com/OpenShot/libopenshot-audio/tree/juce5

**Comment by jonoomph** [comment]
@ferdnyc, Here is the build output from GitLab for the libopenshot-audio juce5 branch. All of the OSes failed to build. Not sure if I merged it incorrectly, or if this is a result of our older Ubuntu builder having old libraries?

* Linux: [gitlab-linux-build-output.txt](https://github.com/OpenShot/libopenshot-audio/files/3024363/gitlab-linux-build-output.txt)
* Mac: [gitlab-mac-build-output.txt](https://github.com/OpenShot/libopenshot-audio/files/3024374/gitlab-mac-build-output.txt)
* Windows: [gitlab-windows-build-output.txt](https://github.com/OpenShot/libopenshot-audio/files/3024375/gitlab-windows-build-output.txt)

**Comment by ferdnyc** [comment]
@jonoomph 
Thanks, I'll take a look this evening. Dinner's calling now. :wink:

**Comment by ferdnyc** [comment]
@jonoomph 
As far as AudioProcessors go... I'm honestly not sure. The processor classes in [that module](https://docs.juce.com/master/group__juce__audio__processors-processors.html) are powerful, but they're all geared towards a realtime DAW type environment, with a full processing graph and adjustable processing modules implemented as chainable plugins (including GUIs for adjustment). For OpenShot's non-realtime purposes, the utilities in juce_audio_basics along with possibly [juce_dsp](https://docs.juce.com/master/group__juce__dsp.html) (a non-GUI module) might be sufficient and/or better.

**Comment by jonoomph** [comment]
Looks like I needed `-std=c++11` vs `-std=c++0x`. That solves the Linux build. Now working on fixing the ZLIB failures on Mac and Windows builds.

**Comment by jonoomph** [comment]
Okay, made a few small tweaks to the CmakeLists.txt and now all 3 OSes are building for libopenshot-audio `juce5` branch! Now I'm moving on to your libopenshot `juce5` branch!

**Comment by jeffski** [comment]
Great effort, look forward to seeing this in the develop branch.

**Comment by ferdnyc** [comment]
@jonoomph Aha, this one's pretty basic: The last two commits I used to enable the C++11 standard in the compiler are CMake 3.1+ features, which gitlab's cmake doesn't recognize. It must still be cmake 2 (as I think we'd previously discovered), which renders so much of cmake's featureset inaccessible. As the _Modern CMake_ book [notes](https://cliutils.gitlab.io/modern-cmake/chapters/features/cpp11.html):
> C++11 is supported by CMake. Really. Just not in CMake 2.8, because, guess what, C++11 didn't exist in 2009 when 2.0 was released. As long as you are using CMake 3.1 or newer, you should be fine, there are two different ways to enable support. And as you'll soon see, there's even better support in CMake 3.8+.

(I didn't even use the 3.8 form. The `CMakeLists.txt` on the branch should be compatible with any cmake from version 3.1 to the current 3.12. Just not version 2.darkages.)

I guess the workaround, if it absolutely comes down to it, would be to manually specify the necessary compiler flags. But turning to _Modern CMake_ again, a big red-tinted "Alert!" admonishment at the bottom of the same page warns:
> ❗ Don't set manual flags yourself. You'll then become responsible for mainting correct flags for every release of every compiler, error messages for unsupported compilers won't be useful, and some IDEs might not pick up the manual flags.

So, before attempting that I'm going to go on a bit of a web crawl to figure out whether there's _any_ possibility of convincing Gitlab-ci to use cmake 3.x, instead of whatever ancient cmake 2 is currently in use. Building under cmake 2 is broken, and avoiding all of the 3.x series' useful features just because they're not supported in an ancient release doesn't benefit OpenShot in any way.

**Comment by ferdnyc** [comment]
\*sigh* I need to learn to refresh before commenting.

**Comment by ferdnyc** [comment]
[This commit](https://sync.vki.ac.be/mpp/mutationpp/commit/92df5d2ea63dbb9b1ed750bae408dc2f1e63a16e) to a different, random project seems to imply that fixing this on Gitlab might be as easy as changing `cmake` to `cmake3` in the `.gitlab-ci.yml` file. Which would be _immensely_ preferable to manually setting compiler flags.

**Comment by ferdnyc** [comment]
@jonoomph 
Yeah, Gitlab's documentation is a _nightmare_, so I'm not going to come up with anything remotely like a definitive answer on how the build environments are configured, what commands are available, etc. I assume that info is maybe accessible from Gitlab UI pages that I can't see, but it sure isn't in their docs.

So, here's a PR (#38) to use `cmake3` as the cmake command in all of the build scripts. If it works, that'd be awesome and we can stop sabotaging the build configs by hacking around cmake 2's lack of features.

**Comment by jonoomph** [comment]
The GitLab runners are all systems configured and managed by me. So, in order for this to work, I just need to make sure cmake3 is installed correctly on those systems, and that it's on the PATH. Otherwise, I think it should be fine. I'll look into this.

**Comment by jonoomph** [comment]
@ferdnyc , here is the state of cmake on our builders:

**Mac Builder:** cmake (version 3.2.3)
**Windows Builders:** cmake (version 3.10.1)
**Linux Builder:** cmake (was version 2.8.12.2, upgraded to 3.2.2)

However, all of these cmake versions are using the command name `cmake` and not `cmake3`. Now, our daily and stable **PPA** only requires "cmake", and does not specify a version. So, newer distros should be fine, but Ubuntu 14.04 will probably need to be decommissioned on the PPA (or it will probably break, since it includes cmake 2.8.12.2)

**Comment by ferdnyc** [comment]
That's awesome! With the switch to cmake3, the commits I added towards the end to add `CXX_STANDARD 11` and `CXX_STANDARD_REQUIRED YES` to the build target properties should be all that's required for libopenshot-audio to compile properly, no manual `-std=c++11` arguments needed. We can also begin adopting all of the _other_ build enhancements that have fallen to the wayside simply because they depend on CMake 3.x features.

As far as Ubuntu 14.04, it reaches its 5-year EOL... [huh, later this month](https://lists.ubuntu.com/archives/ubuntu-announce/2019-March/000241.html) by coincidence. LTS doesn't mean infinite support, fortunately.

I had just pushed a commit onto this PR's branch raising the `CMakeLists.txt` files' version requirement to 3.1, so that it'll be clear to anyone who attempts building with cmake 2.x why things are failing. But I'll go peel that off into a new PR, since this one is closed.

**Comment by ferdnyc** [comment]
> I had just pushed a commit onto this PR's branch raising the `CMakeLists.txt` files' version requirement to 3.1, so that it'll be clear to anyone who attempts building with cmake 2.x why things are failing. But I'll go peel that off into a new PR, since this one is closed.

Which will necessitate some additional changes, turns out, because setting the minimum version to 3.1+ disables some 2.x compatibility features that our `CMakeLists.txt` files are still [ab]using, like manually setting `${PROJECT_VERSION}` before calling `project()`. The 3.x version of the command has a `project(name VERSION x.y.z)` form that overrides `${PROJECT_VERSION}`. But I actually did these fixes months ago and had to throw them away because of the 2.x compatibility requirement, I'll see if I can dig them up again.

**Pull request merged**
