### PR TITLE
Generate JUCE headers during build

### LINKED ISSUE #55: Generate a version include, for library consumers?
So, I'm thinking that... _eventually_, at some point down the road — and with no real urgency — we'll want to start generating a version header from CMake, the same way we do for libopenshot.

I know, I know: I'm the one who **removed** the version header, on the grounds that it wasn't being used for anything. And, it _wasn't_, which is why this isn't urgent at all. 

But, there's one place we _could_ be using a version header, if we had one: `FindOpenShotAudio.cmake`.

Currently, the `FindOpenShotAudio.cmake` we have in libopenshot doesn't support version detection, reporting, or requirements. But if we wanted to _add_ any of that, basically every `FindXXX.cmake` script handles version detection for library dependencies the same way:
1. Detect the library's availability by finding its include directory in the usual fashion
2. Load the library's public header file from that include path
3. Read the version information from that header

It makes sense for libopenshot-audio to handle "publishing" its version information the same way. So _eventually_ we should do that.

We can just copy-paste what libopenshot does to generate _its_ version header, so it's really a simple fix. But there's also no point in rushing to do it, since it won't be useful until we also enhance `FindOpenShotAudio.cmake` to use that version information.

### PR DESCRIPTION
**Pull request by ferdnyc**
After puzzling over how to handle this for a while, I finally hit on it.

The header files in `JuceLibraryCode/` contain hardcoded version info and other data that we'd rather populate from CMake anyway. But editing the files in that directory is a bad idea, since ProJucer would overwrite them the next time we updated the library.

So, I copied both of those files to `/include/` as `.h.in` templates, made updates to `JuceHeader.h.in` to insert the necessary CMake template expressions, and added code to `CMakeLists.txt` to generate the final headers during the build. This is the same process libopenshot uses to generate its `include/OpenShotVersion.h`.

(`include/AppConfig.h.in` is actually not templated, CMake will simply copy it and remove the `.in` extension. But this only works if we keep both files together.)

This means that `include/libopenshot-audio/JuceHeader.h` in an installed libopenshot-audio
will contain current version data generated during the build, and can be used for version detection by dependents, including libopenshot's `FindOpenShotAudio.cmake` module.

Since the header files in `JuceLibraryCode/` are no longer actually used by libopenshot-audio, for clarity a file `JuceLibraryCode/THESE_HEADERS_ARE_IGNORED` is added, which contains a note pointing to `../include/*.h.in`. Whenever we regenerate `JuceLibraryCode/` with ProJucer, we just need to remember to sync up the copies in `/include/` with any changes it makes to the headers. (And recreate the `THESE_HEADERS...` file, if ProJucer deletes it.)

Fixes #55

### CODE REVIEW

**Comment by ferdnyc** [comment]
Whoops. I think CMake's `math(EXPR...)` command only has `OUTPUT_FORMAT HEXADECIMAL` in recent versions. I'll add a version check and figure something out.

**Comment by jonoomph** [comment]
@ferdnyc We should probably add some documentation in our README.md or docs/* somewhere, on how to update things with ProJucer. Or maybe the wiki would be better: https://github.com/OpenShot/libopenshot-audio/wiki/Update-JUCE-Files.

**Comment by jonoomph** [comment]
Merging this into an official repo branch... so I can test on all 3 builders.

**Comment by ferdnyc** [comment]
UGGGH. I really do hope Travis improve on _this_ at some point:

image

But we make so few commits to this repo, I still think the macOS building is worth it despite the _much_ longer wait times.

**Pull request merged**
