### PR TITLE
Fix spelling of ASIO in CMakeLists.txt

### PR DESCRIPTION
**Pull request by ferdnyc**
It doesn't TECHNICALLY matter what this variable is called, since it's purely internal use. It could be named `FEED_ME_DINNER` and everything would work exactly the same.

But, trying to build libopenshot-audio on Windows, I spent **_so much time_** trying to figure out **what** "AISO" even **was**, until I finally noticed that it was trying to pull in ASIO libraries, and realized it was just ASIO misspelled. Once I saw that, it only took me a few moments to download and unpack the necessary files. This change should save others that pointless confusion.

(Note: This _may_ break build scripts, if any of them set `AISO_SDK_DIR` before running CMake. `installer/build-server.py` in the openshot-qt source doesn't, it just lets it get detected or not automatically. Still, if anything depends on the misspelling it may need correcting there too. Or, I suppose, this could be updated to accept _either_ spelling, for maximum backwards compatibility.)

(Note: This is a resubmission of #11, rebased to the `develop` branch.)

### CODE REVIEW

**Comment by jonoomph** [comment]
I think we can close this one, right?

**Comment by ferdnyc** [comment]
@jonoomph Assuming the PR would still apply cleanly, merging it would be cool. I mean, the name's currently _still_  misspelled... be nice to finally stop seeing "AISO" in the CMakeLists.txt. :laughing: 

If it causes a conflict in one of my other, larger PRs, I'll deal with it on that end.

**Comment by jonoomph** [comment]
Sure thing, I'll merge it!

**Comment by jonoomph** [comment]
Done!

**Pull request merged**
