### PR TITLE
ALSA: Use or create IMPORTED library target

### PR DESCRIPTION
**Pull request by ferdnyc**
As with the previous PR, this links libopenshot-audio with the `IMPORTED` target `ALSA::ALSA`, rather than the associated variables.

However, since CMake prior to 3.12 didn't create the `ALSA::ALSA` target, for backwards compatibility we create it ourselves. Tested with both CMake 3.1 and 3.14.

### CODE REVIEW

**Comment by ferdnyc** [comment]
Man, Travis is having a _day_ today. Their MacOS builders are backed up way worse than usual (and it's usually pretty bad to start with). Well, I'm sure it'll finish eventually.

**Comment by jonoomph** [comment]
@ferdnyc Ooops, this one has conflicts now

**Comment by ferdnyc** [comment]
All fixed up. C'mon, Travis... :stuck_out_tongue_closed_eyes:

**Comment by ferdnyc** [comment]
Merging this, now that conflicts are resolved and Travis has passed the build.

**Pull request merged**
