### PR TITLE
Define version info in CMakeLists.txt

### PR DESCRIPTION
**Pull request by ferdnyc**
Like with OpenShot/libopenshot#253, this PR makes the project's root `CMakeLists.txt` the canonical, authoritative source of the version number data. 

In this case, rather than generating `include/Version.h` from it, the version header is simply deleted. That file was _never_ included in **any** of the source code, it literally existed for no other purpose than to hold the version numbers that the CMakeLists.txt then parsed out via complicated regular expressions. To say that makes no sense is an understatement.

Other changes:

* Those `GLOBAL PROPERTY` entries for `JUCE_WINDOWS`, `JUCE_LINUX`, etc. are removed. Those never had any effect, as CMake properties are not defined during the build. The Juce header files automatically determine the value of the `JUCE_` defines.

* The source file globbing (which was always fragile) is replaced by a list of modules, from which filenames are generated.

* `"-DDEBUG"` is added to the `CXX_FLAGS` for debug builds, and `CMAKE_BUILD_TYPE` is set to "Debug" if not set by the user. (A comment in the `CMakeLists.txt` explains in more detail)

* The `CMakeLists` files are also updated to use `GnuInstallDirs`

In addition, I made the main CMakeLists.txt file less deeply nested and less redundant. The Zlib library lookup, which is done on all three platforms exactly the same way, is moved out of the platform-specific sections. And those sections are changed from:
```cmake
IF(WIN32)
         [windows stuff]
ELSEIF(UNIX)
        IF(APPLE)
                [Mac stuff]
        ELSE()
                [Linux stuff]
        ENDIF()
ENDIF()
```
to:
```cmake
if(WIN32)
        [windows stuff]
endif()
if(UNIX AND APPLE)
        [Mac stuff]
endif()
if(UNIX AND NOT APPLE)
        [Linux stuff]
endif()
```
which is equivalent as, in practice, at most one of those will ever be true.

### CODE REVIEW

**Comment by jonoomph** [comment]
@ferdnyc Rebasing this one also to use a different branch, so our builders can play with these changes and see what happens. I love these changes though... nice work! Now let me see if the builders love them.

**Comment by jonoomph** [comment]
LGTM! This worked fine on all build servers, yay!

**Comment by jonoomph** [comment]
Let me create another PR to merge this into develop.

**Comment by ferdnyc** [comment]
Some time after submitting this I discovered that the PPA build in Launchpad explicitly sets `CMAKE_BUILD_TYPE` to `None` since apparently that's how the Debian package builder rolls, which will defeat my carefully-crafted management of the `-DDEBUG` / `-DNDEBUG` flags. 

But it's actually fine. Like I said in the initial PR, setting a DEBUG define is only _required_ on MacOS. Just... **#AlwaysSomething** 🙄 At some point I'll probably submit a PR adding `-DNDEBUG` to "`None`" type builds as well, just to be safe.

(This patch does wipe out the CMake policy warning about `project()` managing version variables, yay!)
```
dpkg-buildpackage
-----------------

dpkg-buildpackage: info: source package libopenshot-audio
dpkg-buildpackage: info: source version 0.1.7+dfsg1-1
dpkg-buildpackage: info: source distribution unstable
 dpkg-source --before-build libopenshot-audio-0.1.7+dfsg1
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean
   dh_clean
 debian/rules build
dh build
   dh_update_autotools_config
   dh_autoreconf
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/<<BUILDDIR>>/libopenshot-audio-0.1.7+dfsg1'
dh_auto_configure -- -DLIB_SUFFIX="/x86_64-linux-gnu"
	cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr 
-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None 
-DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var 
-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON 
-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON 
-DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" 
-DLIB_SUFFIX=/x86_64-linux-gnu
--------------------------------------------------------------
Determining Version Number (from Version.h file)
--> MAJOR Version: 0
--> MINOR Version: 1
--> BUILD Version: 7
--> SO/API/ABI Version: 6
--> VERSION: 0.1.7

CMake Warning (dev) at CMakeLists.txt:61 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.
```
(The full build log: https://launchpadlibrarian.net/390109830/buildlog_ubuntu-cosmic-amd64.libopenshot-audio_0.1.7+dfsg1-1_BUILDING.txt.gz)

**Comment by ferdnyc** [comment]
@jonoomph 

As an added bonus, I recently discovered that [Travis now supports MacOS building](https://docs.travis-ci.com/user/reference/osx/), and I already have my `libopenshot-audio` fork [building on MacOS](https://travis-ci.com/ferdnyc/libopenshot-audio/builds/116269537) in addition to Linux.

As I screw with the CMake build environment more and more, I'm very conscious of the possibility of unknowingly breaking the MacOS builds, as I know the least about them and I'm completely unable to test changes for myself. So, I definitely think that having CI enabled for additional OSes is a major win.

Configuring libopenshot to build the same way will be slightly harder, since by default Travis runs "matrix" builds, meaning it will try to build in every combo of (build config, OS) by default. I don't know if testing all of FFmpeg 2, 3, **and** 4 on MacOS is even _possible_. 

But once I get it sorted out, I'll submit PRs to both repos adding "`osx`" build type configs to their `.travis.yml` files, so we can take advantage of that. (Now, if only they did Windows....)

**Comment by ferdnyc** [comment]
> (Now, if only they did Windows....)

[Travis also does Windows!](https://docs.travis-ci.com/user/reference/windows/) (Damn, I should've wished for something bigger.)

**Pull request merged**
