### PR TITLE
Bump version info for development

### PR DESCRIPTION
**Pull request by ferdnyc**

### CODE REVIEW

**Comment by ferdnyc** [comment]
Now, if Travis' Mac builder would be so kind as to run... :unamused:

**Comment by jonoomph** [comment]
LGTM

**Comment by ferdnyc** [comment]
FINALLY. Merging.

**Comment by ferdnyc** [comment]
(The "FINALLY" was for Travis, not you. :wink: )

**Comment by jonoomph** [comment]
I've kicked off the daily libopenshot-audio PPA building

**Comment by ferdnyc** [comment]
Ooh, excellent, I should've waited for that before restarting OpenShot/libopenshot#408. Oops. :laughing:

**Comment by ferdnyc** [comment]
Hmm, looks like [it built](https://launchpad.net/~openshot.code/+related-packages) as `libopenshot-audio-0.1.8`... instead of `1.0.9`, but I suppose I don't care as long as it contains the correct version info internally.

**Comment by jonoomph** [comment]
Yeah, I haven't bumped the version in the Debian packaging yet... I think it's okay for the moment though. It still hasn't published them to the PPA yet though.

**Comment by ferdnyc** [comment]
Mmm. Might be a good idea to bump them, though, since then it'd show `libopenshot-audio7` as the version pulled in. (Travis just installs `libopenshot-audio-dev` and lets it pull in whatever, so in theory it won't matter, but... better if the right info is attached, I guess?)

**Comment by jonoomph** [comment]
I'm just worried about bumping the version on develop (2.4.5-dev) to a larger version than our release branch (2.4.5), and then the PPA installing develop over release. I need a better PPA release flow if we plan on continuing to support a PPA I suppose.

Normally, after the official release, I merge `release` into `master`, and then into `develop`. The PPA build servers are normally pointed to `develop`, so they pick up the changes then (which will already collide with our -dev version number). Then I update the Debian packaging to reflect the new stable release numbers. Once that has been built, I copy all 3 packages from the daily PPA to the stable PPA (i.e. since the daily is the official release for a brief moment in time).

**Comment by jonoomph** [comment]
libopenshot-audio updated and published on PPA

**Comment by ferdnyc** [comment]
> I'm just worried about bumping the version on develop (2.4.5-dev) to a larger version than our release branch (2.4.5), and then the PPA installing develop over release.

Mmm, that makes sense. Well, we'll see if Travis is happy, if it is then meh... who cares? :laughing:

**Comment by ferdnyc** [comment]
It loaded the new build, looks good.

**Pull request merged**
