### PR TITLE
fix Juce header file's isfinite() semantics

### PR DESCRIPTION
**Pull request by ferdnyc**
Fixes: OpenShot/libopenshot#42

Crap, I can't believe I never submitted a PR for this, and the issue's still present in 0.1.6. It was very early on in my involvement and I hadn't started working with the library code yet.

When building the previous release of libopenshot on Fedora (then) 27, I ran into an issue that @firew4lker reported over in libopenshot, which I eventually tracked down to an issue with the a Juce header file included with libopenshot-audio, which was causing libopenshot to FTBFS. The fix was trivial, you can see it in [my comment on that bug](https://github.com/OpenShot/libopenshot/issues/42#issuecomment-367256437).

But it never made it into the libopenshot-audio source. So, I guess better late than never... sorta.

### CODE REVIEW

**Comment by jonoomph** [comment]
I'm guessing this will no longer apply after I update JUCE (I think). I'll revisit this soon.

**Comment by ferdnyc** [comment]
@jonoomph Yeah, TBH  I don't know. Those template functions are _identical_ in the latest code, so unless the root cause of the issue (whatever that may be) was fixed elsewhere in the codebase, it might still be needed.

I'd of course _prefer_ to figure out exactly WHY the code doesn't work as-is, since I never really understood why the fix fixed the issue, or why it was happening in the first place. But I guess we won't know whether it still trips up the libopenshot build until we have a libopenshot-audio built with the new Juce, and can try using it to build libopenshot.

**Comment by ferdnyc** [comment]
@jonoomph 
Yeah, no, the new Juce code still has exactly the same issue, so this fix (or some other/better one) is still needed.

I'm coming to the conclusion that the issue is being created by the Ruby header files, specifically — the clue is in the exact content of the error message:
```
/usr/include/libopenshot-audio/juce_core/maths/juce_MathsFunctions.h:
 In function ‘bool juce::juce_isfinite(NumericType) [with NumericType = double]’:
/usr/include/libopenshot-audio/juce_core/maths/juce_MathsFunctions.h:459:17:
 error: ‘finite’ is not a member of ‘std’
     return std::isfinite (value);
                 ^~~~~~~~
/usr/include/libopenshot-audio/juce_core/maths/juce_MathsFunctions.h:459:17:
 note: suggested alternative: ‘isfinite’
```

I didn't really catch on to this before, but it doesn't say "'isfinite' is not a member of 'std'", it says "**'finite'** is not a member of 'std'". But... when did we ever mention 'finite'?

We didn't. But, in the Ruby header file `/usr/include/ruby/missing.h`, they do a bunch of `#define`s, including:
```h
#ifndef isfinite
# ifndef HAVE_ISFINITE
#   define HAVE_ISFINITE 1
#   define isfinite(x) finite(x)
# endif
#endif
```

I'm _still_ not sure why that would (apparently) also redefine `std::isfinite` as `std::finite`, since isn't the whole point of namespaces supposed to be that they protect against this kind of nonsense? I kind of feel like if `#define`s will be expanded _regardless of namespace prefixing_, but can then be overridden by a `using namespace` directive, then precedence is messed up somewhere in the C++ standard.

Regardless, this code still breaks building the ruby bindings:
```c++
template <>
inline bool juce_isfinite (float value) noexcept
{
   #if JUCE_WINDOWS && ! JUCE_MINGW
    return _finite (value) != 0;
   #else
    return std::isfinite (value);
   #endif
}
```
...while _this_ code is inexplicably fine...
```c++
template <>
inline bool juce_isfinite (float value) noexcept
{
   #if JUCE_WINDOWS && ! JUCE_MINGW
    return _finite (value) != 0;
   #else
    using namespace std;
    return isfinite (value);
   #endif
}
```

**Comment by ferdnyc** [comment]
Also fine, as I just discovered, is this variation:
```c++
template <>
inline bool juce_isfinite (float value) noexcept
{
   #if JUCE_WINDOWS && ! JUCE_MINGW
    return _finite (value) != 0;
   #else
    using std::isfinite;
    return isfinite (value);
   #endif
}
```
...which I think I like a lot better. (Though now it makes even _less_ sense to me why we'd be seeing this behavior.) Anyway, dealer's choice on the exact form, but either way it appears we do still need to massage that Juce header if we want to keep the Ruby bindings happy.

**Comment by jonoomph** [comment]
@ferdnyc Do we still need to merge a fix for this (for Ruby)? Or is the fix already applied to `develop`? Just double checking. Thx!

**Comment by ferdnyc** [comment]
@jonoomph  Nope, it went in as part of the `juce5` branch changes.

**Pull request closed without merging**
