### PR TITLE
Update formatting for commit logs

### PR DESCRIPTION
**Pull request by ferdnyc**
Some more tweaks to the log-o-commits formatting, when generated by the GitLab builders:

* The actual format string is stored in an environment variable, to avoid retyping four times
* MarkDown-friendly output (including the leading '`- `' on each line), so that the file contents can be directly cut-and-pasted into a Release description
* Removed all of the color escapes, since they're pointless while redirecting the output
* Removed the branch/tag labels for commits as unnecessary information
* Fields rearranged to non-columnar format (making width limits unnecessary)
* `--pretty=tformat:` is used, to ensure a trailing newline
* `--no-merges` added, to reduce clutter

Here's an example run in the libopenshot repo:
```console
$ GIT_LOG_FORMAT="- %h %ad %s [%aN]" git log $(git describe --tags --abbrev=0 "@^^")..HEAD\^1 --oneline --date=short --no-merges --pretty="tformat:$GIT_LOG_FORMAT"
- 6a95693 2020-03-03 Adding -dev2 to version (merging master back to develop) [Jonathan Thomas]
- 16991bf 2020-02-29 Release branch for 0.2.0 (SO 7) [Jonathan Thomas]
- 005be5a 2020-02-29 CMake: Add hex-version helper source (#89) [Frank Dana]
- b8d1988 2020-02-28 Travis: Remove homebrew (too slow) (#87) [Frank Dana]
- 7680f36 2020-02-28 Accidental version revert [Jonathan Thomas]
- 2af598d 2020-02-28 Fix broken hex logic [Jonathan Thomas]
- 1bbc5fe 2020-02-28 Updating HEX version for 0.2.0: 0x200 [Jonathan Thomas]
- c18798e 2020-02-28 Take 2, bump verison to 0.2.0-dev1 [Jonathan Thomas]
- 4542616 2020-02-28 Bump version on libopenshot-audio to 0.2.0 [Jonathan Thomas]
- 153565e 2020-02-26 Main.cpp: std prefixes, use juce::Thread::sleep() [FeRD (Frank Dana)]
- a90fc5a 2020-02-08 Merging master into develop [Jonathan Thomas]
- 5f30647 2020-01-07 Bump version info for development [FeRD (Frank Dana)]
```

And, if I cut-and-paste that text here:

- 6a95693 2020-03-03 Adding -dev2 to version (merging master back to develop) [Jonathan Thomas]
- 16991bf 2020-02-29 Release branch for 0.2.0 (SO 7) [Jonathan Thomas]
- 005be5a 2020-02-29 CMake: Add hex-version helper source (#89) [Frank Dana]
- b8d1988 2020-02-28 Travis: Remove homebrew (too slow) (#87) [Frank Dana]
- 7680f36 2020-02-28 Accidental version revert [Jonathan Thomas]
- 2af598d 2020-02-28 Fix broken hex logic [Jonathan Thomas]
- 1bbc5fe 2020-02-28 Updating HEX version for 0.2.0: 0x200 [Jonathan Thomas]
- c18798e 2020-02-28 Take 2, bump verison to 0.2.0-dev1 [Jonathan Thomas]
- 4542616 2020-02-28 Bump version on libopenshot-audio to 0.2.0 [Jonathan Thomas]
- 153565e 2020-02-26 Main.cpp: std prefixes, use juce::Thread::sleep() [FeRD (Frank Dana)]
- a90fc5a 2020-02-08 Merging master into develop [Jonathan Thomas]
- 5f30647 2020-01-07 Bump version info for development [FeRD (Frank Dana)]

### CODE REVIEW

**Comment by ferdnyc** [comment]
See OpenShot/libopenshot#486 for additional requirements before merging.

**Comment by ferdnyc** [comment]
This is no longer WIP, though it does now depend on OpenShot/openshot-qt#3653 getting merged first.

**Comment by jonoomph** [comment]
@ferdnyc This looks great! There is a conflict, and I'm not sure how to resolve it. I'll let you do this surgery!

**Comment by jonoomph** [comment]
@ferdnyc Okay, I've resolved these conflicts... hopefully. Waiting to see if any failures happen.

**Pull request merged**
