### PR TITLE
Add juce_dsp module

### PR DESCRIPTION
**Pull request by ferdnyc**
This PR enables the `juce_dsp` module for audio processing. It also changes the C++ standard from C++11 to C++14, as required by `juce_dsp`.

### CODE REVIEW

**Comment by BrennoCaldato** [comment]
Thanks @ferdnyc. This saved me some time :)

I am trying it out on the new effects

**Comment by ferdnyc** [comment]
> I am trying it out on the new effects

Just FYI, in cases you weren't already aware, if you create `dsp-module` branches in both the `libopenshot` and `openshot-qt` repos, the Gitlab project builders will generate OpenShot packages using the code on that branch in each repo, which can be a good way to test the results end-to-end. 

(The branch name could be different, of course, but this one would have to be renamed. It only works if the same branch exists in all three repos.)

**Comment by BrennoCaldato** [comment]
Hi @ferdnyc
I tried to merge this or rename the branch but realize I don't have write access to libopenshot-audio. Can you grant permissions for me?


CC: @jonoomph

**Comment by ferdnyc** [comment]
@BrennoCaldato Only @jonoomph can give you commit access, I'm afraid... but in the meantime, I can do the merge for you. I'll take care of that now.

**Comment by BrennoCaldato** [comment]
Thanks @ferdnyc

**Pull request merged**
