### PR TITLE
Adding stale bot for github issue management (libopenshot-audio)

### PR DESCRIPTION
**Pull request by jonoomph**
Experimental support for `stale` plugin, to help with issue management on GitHub.  https://github.com/marketplace/stale

Related PR for libopenshot: https://github.com/OpenShot/libopenshot/pull/460

### CODE REVIEW

**Comment by jonoomph** [comment]
@ferdnyc Would love to hear your comments on default settings. These are mostly the "default" settings the stale bot ships with. I think 60 days seems fair, before tagging an issue as 'stale', and 7 more days to respond also seems reasonable. 

I'm not quite sure what happens though, after someone responds. Does the bot remove the 'stale' label automatically?

**Comment by ferdnyc** [comment]
> @ferdnyc Would love to hear your comments on default settings. These are mostly the "default" settings the stale bot ships with. I think 60 days seems fair, before tagging an issue as 'stale', and 7 more days to respond also seems reasonable.

Yeah, that sounds pretty fair. Might want to raise it to 120 or even 180 days on _these_ repos, since issues tend to languish a lot longer despite being perfectly valid. But for OpenShot, 2 months sounds reasonable.

_Maybe_ the grace period could be raised to 2 weeks, since there actually have been plenty of times where someone's gotten back to an issue (in either direction) after 10 or 12 days have passed... but 7 is probably fine, too.

> I'm not quite sure what happens though, after someone responds. Does the bot remove the 'stale' label automatically?

According to the [marketplace listing](https://github.com/marketplace/stale), yes. :+1: 
> If the Issue or Pull Request is updated, or anyone comments, then the stale label is removed.

Only change I'd request, for all repos, is to add `exemptAssignees: true` to the config, so that assigning an issue to someone will protect it from being Stale'd.

Oh, that, and `only: issues`, if it isn't already set, since we definitely don't want pull requests to get auto-closed after only 2 months. Or probably ever, really. We can manually close those, there's not that many.

**Comment by jonoomph** [comment]
@ferdnyc Updating auto-stale conditions (90 days warning, 10 days to respond, only issues, ignore assigned issues). I feel good about these changes. I'm gonna merge this soon, and see what happens. :crossed_fingers:

**Comment by ferdnyc** [comment]
LGTM. Hell, I'll pull the trigger for you, let's light this candle. :wink:

**Comment by ferdnyc** [comment]
(You'll notice I only did the _one_ repo, because I am a coward. We'll see how this goes...)

**Comment by ferdnyc** [comment]
Oh, hehe, see? The parameters are already out of sync. I have to update the description of the stale label, to reflect the latest changes. :smile:

**Comment by jonoomph** [comment]
Thanks!

**Pull request merged**
