### PR TITLE
WIP: Towards a more modern cmake usage

### PR DESCRIPTION
**Pull request by ferdnyc**
This still-evolving PR attempts to drag our `CMakeFiles.txt` into the cmake-3.1+ world. It also pulls in a few modules from much-newer CMake releases, and uses the modern features of those modules (available in all versions since they're in the repo tree).

I've _attempted_ to account for all supported OSes and architectures, but may have missed some things so I'll be curious to see what the builders do with this. Additionally, I need to further research the OS X definitions for dependencies because I'm pretty sure there's a better way to handle them than this:
```cmake
target_link_libraries(openshot-audio "-framework Carbon -framework Cocoa \
-framework CoreFoundation -framework CoreAudio -framework CoreMidi -framework IOKit \
-framework AGL -framework AudioToolbox -framework QuartzCore -lobjc -lz -framework Accelerate")
```

This PR also incorporates the excellent GNUInstallDirs idea from #21 by @alaviss, and includes the changes from my own #44 and #29 (making them obsolete).

### CODE REVIEW

**Comment by ferdnyc** [comment]
(A note mostly for myself:) I also want to sit down with the `CMakeLists.txt` changes in #10 by @RichiCoder1 and see if there's anything I missed. I _believe_ I've covered most of it here, and the rest of that PR was effectively the `juce5` branch.

**Comment by RichiCoder1** [comment]
A bit late, but LGTM and endorse

**Comment by jonoomph** [comment]
@ferdnyc I think I might move this into a branch, so the builders can play with it before we merge this one... just to verify it all plays nice.

**Comment by ferdnyc** [comment]
@jonoomph 

That sounds cool, it's not really done yet either — but I'd definitely like to find out what problems the builders **will** end up having with it, so I can address them.

**Comment by ferdnyc** [comment]
I'm closing this PR because #50 is a more gentle approach to addressing these issues, and it will conflict with what's here. 

Also, some of this one is out of date now that other PRs were merged, which makes the commit history a confusing mess. Also, some of it's just plain broken. (For starters, it has the same bug I discovered, and fixed, in #50: `include(GnuInstallDirs)` doesn't work right unles it's _after_ `project()`).

**Pull request closed without merging**
