### PR TITLE
WIP: Upgrade to JUCE 5.4.5

### PR DESCRIPTION
**Pull request by ferdnyc**
This is a relatively minor update, _however_ it contains one important fix of importance to us: The input audio device will no longer be initialized if 0 channels are requested, which [is reported](https://forum.juce.com/t/is-there-a-way-to-do-audio-output-only-the-input-and-output-devices-dont-share-a-common-sample-rate/32038/13) to solve this error on Windows:

image

I also bumped the version to `0.1.8-dev2`, though obviously this should be released as 0.1.9. An `SONAME` bump is **not** necessary, nor is an OpenShotAudio minimum version bump for libopenshot. 0.1.8 is fully compatible.

Oh, and I moved the `JUCE_DONT_AUTOLINK_TO_WIN32_LIBRARIES` setting into `include/AppConfig.h`, so there's no reason it needs to be set in any of our CMakeFiles at all.

This PR is submitted from a project-repo branch, **#4DaBuildaz**

### CODE REVIEW

**Comment by ferdnyc** [comment]
> it contains one important fix of importance to us

That's terrible. Who _writes_ this crap!?! :stuck_out_tongue:

**Comment by ferdnyc** [comment]
Hrm. It seems this upgrade fails to build on the OpenShot MacOS builder, due to its XCode and/or SDK installs being an older version JUCE no longer supports. That's unfortunate, as upgrading it is probably the only possible solution.

Given that, and due to the unclear timeframe on any such upgrade, I'm going to try and cherry-pick the fix just for that Windows device issue we've been struggling with. That'll get us through until @jonoomph has a chance to sort out the Mac builder.

**Comment by jonoomph** [comment]
Updating this to WIP for now... not sure exactly what I need to do to fix the Mac builder though... I guess I need to dig into the GitLab logs and see what it needs.

**Comment by ferdnyc** [comment]
@jonoomph Right, so... this.

AFAICT, the issue is that the version of XCode on the OpenShot Gitlab Mac builder is simply too old, and no longer supported by JUCE. The error output from the build is:
```
/usr/bin/clang++   -Dopenshot_audio_EXPORTS -flax-vector-conversions -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -fPIC -I/Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/build/include -I/Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/modules    -std=c++11 -o CMakeFiles/openshot-audio.dir/JuceLibraryCode/include_juce_audio_basics.mm.o -c /Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/include_juce_audio_basics.mm
In file included from /Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/include_juce_audio_basics.mm:9:
In file included from /Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.mm:23:
In file included from /Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.cpp:32:
In file included from /Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.h:52:
In file included from /Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/modules/juce_core/juce_core.h:65:
/Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot-audio/JuceLibraryCode/modules/juce_core/system/juce_TargetPlatform.h:147:8: error:
 "The 10.11 SDK (Xcode 7.3.1+) is required to build JUCE apps. You can create apps
 that run on macOS 10.7+ by changing the deployment target."
      #error "The 10.11 SDK (Xcode 7.3.1+) is required to build JUCE apps. You can create
 apps that run on macOS 10.7+ by changing the deployment target."
       ^
1 error generated.
make[2]: *** [CMakeFiles/openshot-audio.dir/JuceLibraryCode/include_juce_audio_basics.mm.o]
 Error 1
make[1]: *** [CMakeFiles/openshot-audio.dir/all] Error 2
make: *** [all] Error 2
ERROR: Job failed: exit status 1
```

The solutions would (I'm guessing) be:
1. Upgrade MacOS on the machine to something more recent, meaning 10.11 or greater. (No idea what it's running now, but presumably it's an earlier release than that.) Presumably that would bring a more recent XCode and/or SDK that JUCE still supports.
1. Failing that, upgrading just XCode to version 7.3.1 or later — assuming it's possible to download a newer XCode for the MacOS release the builder is running — might fix the issue without having to upgrade the entire OS.

**Comment by ferdnyc** [comment]
I also have to figure out what this means, exactly:
> You can create apps that run on macOS 10.7+ by changing the deployment target.

Since presumably we would, in fact, like our apps to run on macOS 10.7+.

**Comment by ferdnyc** [comment]
Aha. From `juce_TargetPlatform.h`:
```cpp
  #if JUCE_MAC
    #if ! defined (MAC_OS_X_VERSION_10_11)
      #error "The 10.11 SDK (Xcode 7.3.1+) is required to build JUCE apps. You can create apps that run on macOS 10.7+ by changing the deployment target."
    #elif MAC_OS_X_VERSION_MIN_REQUIRED < MAC_OS_X_VERSION_10_7
      #error "Building for OSX 10.6 is no longer supported!"
    #endif
  #endif
#endif
```

...Presumably setting the deployment target in XCode would define `MAC_OS_X_VERSION_MIN_REQUIRED`, which is checked in a bunch of places in the JUCE code... but since we're not using XCode, we can probably just add it as a compile definition in the CMake configs.

**Comment by ferdnyc** [comment]
(And actually, looking at this:)
```cpp
    #if ! defined (MAC_OS_X_VERSION_10_11)
      #error "The 10.11 SDK (Xcode 7.3.1+) is required to build JUCE apps. You can create apps that run on macOS 10.7+ by changing the deployment target."
```
I'm guessing upgrading just XCode alone _wouldn't_ work, and the builder really does have to be running macOS 10.11 or later.

**Comment by ferdnyc** [comment]
And, actually, if we _do_ do this (upgrade the builder to 10.11+ and set compatibility to 10.7 via `MAC_OS_X_VERSION_MIN_REQUIRED`) then we should skip 5.4.5 in favor of (at least) 5.4.6, where one of the [release note line items](https://github.com/WeAreROLI/JUCE/releases/tag/5.4.6) is:
> * Fixed compatibility with macOS versions below 10.11

...5.4.7 is now out, as of 2020-02-10, so it would make sense to move to that version. But, still, that'll only work if the Gitlab Mac builder is upgraded.

**Comment by ferdnyc** [comment]
Closing this in favor of #88.

**Pull request closed without merging**
